#! /bin/sh
source config-dist.sh

echo === Creating $MYSQL_DATABASE database

$MYSQL_COMMAND << EOF
DROP DATABASE IF EXISTS $MYSQL_DATABASE;

CREATE DATABASE $MYSQL_DATABASE DEFAULT CHARACTER SET UTF8;

GRANT ALL ON $MYSQL_DATABASE.* TO $MYSQL_USER@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL ON $MYSQL_DATABASE.* TO $MYSQL_USER@'127.0.0.1' IDENTIFIED BY '$MYSQL_PASSWORD';
EOF
